{
    "name": "DRIFT Rest Coach",
    "summary": "Odoo-native PWA backend for Strava-based rest recommendations.",
    "version": "1.0.0",
    "category": "Website",
    "author": "DRIFT",
    "website": "https://olivierstrails.com",
    "license": "LGPL-3",
    "depends": ["website", "website_sale", "portal", "auth_signup"],
    "data": [
        "security/ir.model.access.csv",
        "security/drift_record_rules.xml",
        "data/drift_seed_data.xml",
        "views/product_template_views.xml",
        "views/drift_menu_views.xml",
        "views/drift_templates.xml",
    ],
    "assets": {},
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
}
